### ISSUE TITLE
DSC Configuration 'DomainController' completed with error(s)

### ISSUE THREAD

**Issue by akhileshnirapure** [Azure-Samples/active-directory-lab-hybrid-adfs#10]
Hi, 

I get this when i deploy the template with "no/with clients" option.

`{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "VMExtensionProvisioningError",
                "message": "VM has reported a failure when processing extension 'Microsoft.Powershell.DSC'. Error message: \"DSC Configuration 'DomainController' completed with error(s). Following are the first few: No match was found for the specified search criteria for the provider 'NuGet'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags. No match was found for the specified search criteria for the provider 'NuGet'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags. No match was found for the specified search criteria and provider name 'NuGet'. Try 'Get-PackageProvider -ListAvailable' to see if the provider exists on the system.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot "
            }
        ]
    }
}`

**Comment by diwu1** [comment]
I hit the same error when deploy the template with 'Full deploy - AD, ADFS, WAP'. Is there any update on this issue? Thanks!

**Comment by Gopal-y5** [comment]
Hi  Team,
Please could you update Nuget package version from 2.8.5.201 to either 2.12.1 or 2.8.6 in the lab-hybrid-adfs/DSC/adDSC/adDSCConfiguration.ps1 file. Which might resolve above issue.  Please if you update this, it'll be really helpful.

**Comment by markmcdon7** [comment]
I had same problem when using the 'Deploy to Azure' website button.

**Comment by ghost** [comment]
Same error here with the original Configuration files. Changing the NuGet to 2.12.1 did not solve my issue.

**Comment by mikewo** [comment]
I believe the issue is related to PSGallery changing its policy to only TLS 1.2 or higher to connect. By default PowerShell uses TLS 1.0. There is  PR up (linked above) that forces the two scripts that use PSGallery to install packages to use TLS 1.2.
