### ISSUE TITLE
Validation error when deploying template

### ISSUE THREAD

**Issue by oskarm93** [Azure-Samples/active-directory-lab-hybrid-adfs#2]
I received this validation error when attempting to deploy the first link template.
I think it has to do with multi-dotted FQDN (sub.domainname.com):
"companyNamePrefix": "[split(parameters('adDomainName'),'.')[0]]",

![image](https://user-images.githubusercontent.com/4509839/30112610-e18372e8-9309-11e7-8d25-677f6c9f960e.png)

**Comment by bretthacker** [comment]
Yes, the default naming for the DC appends "dc1" to the AD domain name, then the ARM engine verifies that the DNS name for the region (which would be &lt;ad domain&gt;dc1.&lt;region&gt;.cloudapp.net) is available...you hit the jackpot. Try another region, change the AD name, or fork the template and change the name... :)
